### PR TITLE
Simple Tkinter GUI app using caer and matplotlib

### PR DESCRIPTION
**Pull request by GitHubDragonFly**
### Description

- Simple Tkinter GUI app using caer and matplotlib
- Designed to manipulate only the "Sunrise" image shipped with caer
- Shows functionality of some features from the current examples
- Should be used only as a base to create more featured and complex GUI
- Intended for those who might need help starting a GUI project

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [x] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### Checklist:

- [x] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `dev` and not `master`
- [ ] I will squash merge this PR into `dev` (optional)

### CODE REVIEW

**Review by jasmcaus — CHANGES_REQUESTED** [review]
Great initiative @GitHubDragonFly! 

Couple of things I'd like to point out though:
1. Are the Hue, Saturation and Motion Blur options supposed to be sliders? They don't seem to slide either way (see image)
2. Could you kindly point the target file to the `examples/` folder
3. Change the target branch to `dev`
4. Most importantly, could you give the user the option to select any image they'd like? Currently, it targets `caer`'s `sunrise` image?

image

**Comment by GitHubDragonFly** [comment]
The sole purpose of this example is to show users how to go about incorporating caer features into a GUI project.

Sliders work fine in my test with Windows 10 and python 3.6.8 (they are only enabled when the "Original" button is selected).

There was a bug related to anchors which I just fixed and this file is already in the "examples" folder on my fork.

I wouldn't be looking to make any more changes to this.

**Comment by jasmcaus** [comment]
Right, and I think that added functionality would be more beneficial to the user. The program is great, it's a great showcase, but it's limited - I'm not quite sure a user would want to experiment solely on the `sunrise` image. Anyway, I'll leave that up to you. If you feel up to it, by all means. 

Whether you make updates to the above or not, I would still encourage you to add a little writeup explaining your app (like how to set it up, how to use the options...). I'm sure it's pretty explanatory, but you can maybe fit it in a para or two [here](https://github.com/jasmcaus/caer/blob/master/examples/README.md). I could do it too, but I'd much rather you, the creator, do it.

**Comment by GitHubDragonFly** [comment]
This latest commit is refined version, with "Gamma" feature replacing "Motion Blur".
Tested as working in both Windows and Linux.

Some of your features don't work properly in tkinter, like adjust_brightness which puts a pink overlay and requires rather small values to show that it's changing (0.0025 to 0.005). This should be applicable to brighten and darken features as well.

There are comments in the file itself that explain how to run the app so you can grab them and paste them in your file.

If you have no interest in including this file as it is then let me know and I will put it in my own repo.

**Review by jasmcaus — APPROVED** [review]

**Comment by jasmcaus** [comment]
LGTM. 

Thanks for this @GitHubDragonFly!

**Pull request merged**
