### PR TITLE
Updating Caer Copyright

### PR DESCRIPTION
**Pull request by MalikMAlna**
### Description

- Updating Caer Copyright from 2020 to 2021 for all instances of commented year
- Did not update/touch upon any other copyright in project directory

### Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [x ] Docstrings/Documentation updated

### Related Issues

https://github.com/jasmcaus/caer/issues/17

### Checklist:

- [x ] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [x ] I have updated the documentation accordingly.
- [x ] This PR is being made to `staging` and not `master`
- [ ] I will squash merge this PR into `staging` (optional)

### CODE REVIEW

**Comment by jasmcaus** [comment]
Hi @MalikMAlna, great spotting! Was too busy working on breaking issues, that it completely slipped my mind that we're in the New Year. 

I see you've changed `2020 ==> 2021`. Could you instead change it to `2020 ==> 2020-2021`? That's a better representation, I feel. 

Also, I've changed the base branch from `staging` to `dev` because that's where I add updates to `Caer`.

**Comment by MalikMAlna** [comment]
Sounds good! Will add that update and push it in sometime before the end of today.

**Comment by MalikMAlna** [comment]
There you go!

**Comment by jasmcaus** [comment]
Thanks for your patch, @MalikMAlna! I've added you as a contributor to this repo. Feel free to open a PR at any time if you have any more contributions. Cheers :)

**Pull request merged**
