### PR TITLE
[FEATURE] Added LUV colorspace

### LINKED ISSUE #21: [Feat] Add support for the LUV colorspace in `caer.color`
Add support for the LUV colorspace in `caer.color`

Open for contributions :)

### PR DESCRIPTION
**Pull request by lucasace**
### Description
Added the luv colorspace to the set of existing colorspaces, also added tests for the same

### Types of changes

- [x] New Feature to Caer
- [x] New tests added to cover the changes

### Related Issues

Fixes #21 

### Checklist:

- [x] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [x] I have added tests covering my contributions (**important**).
- [ ] I have updated the documentation accordingly.
- [x] This PR is being made to `dev` and not `master` (**important**).
- [ ] I will squash merge this PR into `dev` (optional)

### CODE REVIEW

**Comment by jasmcaus** [comment]
I need to sit down and read through this properly - see why tests are breaking. 
In the meantime, could you please change the `"` to `'` in the strings? I'm rather finicky about this ;)

**Comment by lucasace** [comment]
> I need to sit down and read through this properly - see why tests are breaking.

I did my inspection, i cannot figure out why its breaking
Also the extra 4 commits wont go and its kinda pointless for it to merge with dev, do u need me to open another pr? 
> In the meantime, could you please change the `"` to `'` in the strings? I'm rather finicky about this ;)
Oops , i think `black` did that while formatting 🤦🏽, ill give it a fix

**Comment by jasmcaus** [comment]
No, not required. I'll see what I can manage. I suspect the error has something to do with the `cspace` attributes in the `caer.Tensor`

**Comment by jasmcaus** [comment]
LGTM! Thanks much for this, @lucasace! Your contribution is always appreciated :)

**Pull request merged**
